#!/bin/ksh
print "-------------------"
print "Process starting..."
print "-------------------"

export LOG_DIR=/opt/filegateway/log
NOW=`date +%Y%m%d`
export LOG_FILE=${LOG_DIR}/${NOW}_sniffer_job.log

### Checking the number parameters passed ###

if [[ "$#" -eq 2 ]];
then
  export env=${1}
  export sqs_name=${2}
else
  echo "Either Mandatory parameters are not passed or incorrect number of parameters passed..."
  echo "Missing mandatory parameters ..pass to the script ...exiting with error code 1.." >> ${LOG_FILE}
  exit 1
fi

######################################################################
# Exporting environment and project related params
######################################################################

. /opt/filegateway/scripts/setenv.ksh ${1}

######################################################################
python2 /opt/filegateway/scripts/test.py ${2}
ret=$?
if [ $ret -ne 0 ]; then
	echo "Missing mandatory parameters or autorization error"
	echo "Please validate all the arguments as required."
	echo "ksh <d_sts_ece_fg_sniffer.ksh> <env> <sqs_name>"
	exit 1
else
	echo "Sniffer job is completed"
	echo "Process completed"
	exit 0
fi
